### PR TITLE
v3.1x.x-dev-pre-rev-0

### PR DESCRIPTION
**Pull request by taoteh1221**
v3.1x.x-dev-pre-rev-0

### CODE REVIEW

**Comment by thisisawesome1994** [comment]
Will it include alphavantage stock tickers aawell? Because I think I want to open a feature request for the ticker on the rpi4 screensaver. It is awesome on my living room television, with a Chinese 4 screen multiviewer. Are you planning on adding alphavantage support for stocks?

**Comment by taoteh1221** [comment]
> Will it include alphavantage stock tickers aawell? Because I think I want to open a feature request for the ticker on the rpi4 screensaver. It is awesome on my living room television, with a Chinese 4 screen multiviewer. Are you planning on adding alphavantage support for stocks?

I'll probably be adding alphavantage API support eventually, not sure when though. I'm not sure if it would integrate with a raspi os screensaver though? It could if you can open a local web page in a screensaver app (~/slideshow-crypto-ticker/index.html).

**Comment by thisisawesome1994** [comment]
No, I mean in the ticker (screensaver). So that it displays in the screensaver, but updates every minute or so.

**Comment by taoteh1221** [comment]
> No, I mean in the ticker (screensaver). So that it displays in the screensaver, but updates every minute or so.

Got it. Yeah, whenever I eventually add it, you'll be able to choose how many minutes between re-checks.

**Comment by taoteh1221** [comment]
looks good

**Pull request merged**
